image: gitpod/workspace-python-3.11

additionalRepositories:
  - url: https://gitlab.maklai.dev/pytools/pyconf.git
    checkoutLocation: qa-api/.pyconf
tasks:
  - name: init
    before: |
      sudo tailscaled & sudo -E tailscale up --authkey=${TAILSCALE_AUTHKEY} --accept-routes
      echo ${GITLAB_TOKEN} | docker login -u ${GITLAB_USER} --password-stdin registry.maklai.dev & sudo apt install git-lfs
    init: |
      poetry run .pyconf/scripts/setup_dev_env.sh
      poetry install
      git-lfs pull
      touch app/.env.dev
      echo "# Replace empty quotes with your own values:" >>  app/.env.dev
      echo "BOT_TOKEN=\"\"" >>  app/.env.dev
      echo "SIGNING_SECRET=\"\"" >>  app/.env.dev
      echo "OPENAI_API_KEY=\"\"" >>  app/.env.dev
      docker-compose pull
      docker-compose build
      docker-compose up

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.isort
    - donjayamanne.python-extension-pack
    - matangover.mypy
    - ms-azuretools.vscode-docker
    - bungcip.better-toml
    - aaron-bond.better-comments
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
    - GitHub.copilot
    - samuelcolvin.jinjahtml
    - eamodio.gitlens

ports:
  - name: knowledgeBaseQA
    port: 8000
    onOpen: notify
    visibility: public
