version: "3.8"

services:
  knowledgebase-app:
    container_name: app
    command: uvicorn app.main:fastapi_app --log-config=/app/configs/logging.yaml --reload --host=0.0.0.0 --port=8000
    build:
      context: .
    environment:
      ENVIRONMENT: development
      load_dotenv: True
      PYDEVD_DISABLE_FILE_VALIDATION: 1
    volumes:
      - ./:/app
    ports:
      - 8000:8000
      - 5000:5000
