livenessProbe:
  httpGet:
    path: /healthz
    port: 8000

readinessProbe:
  httpGet:
    path: /healthz
    port: 8000

main_resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1500"
