main_resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    memory: 4Gi

hpa:
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90

ingress:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: null
  addUrls:
    - http://knowledgebase-app.maklai.co/
